version: '3'
volumes:
  db_data:
services:
  database:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_multi_tools_pdf_extractor
      MYSQL_USER: hallan
      MYSQL_PASSWORD: 12qwaszx
    ports:
      - "3306:3306"
    volumes:
      - db_data:/db_multi_tools_pdf_extractor
    networks:
      - network_api

networks:
  network_api:
    driver: bridge