version: "3.9"

volumes:
  mysql_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "app"]
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./:/app
    environment:
      DB_DATABASE: db_multi_tools_pdf_extractor
      DB_USER: hallan
      DB_HOST: mysql
      DB_PASSWORD: 12qwaszx
    networks:
      - my_network_api

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_multi_tools_pdf_extractor
      MYSQL_USER: hallan
      MYSQL_PASSWORD: 12qwaszx
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network_api

networks:
  my_network_api:
    driver: bridge
      